# Generated by Django 3.1.4 on 2020-12-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20201226_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='remaining_datetime',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='remaining_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
